### ISSUE TITLE
retrieving metrics data from postgres via a client

### ISSUE THREAD

**Issue by Haybu** [timescale/prometheus-postgresql-adapter#11]
I am using kubernetes, and I'm able to use the adapter just fine to write to postgres. In prometheus, all metrics are retrievable. I exposed my database service via a LoadBalancer type and connected to it using a client from my laptop. Connection is successful, and I can see the schema with all tables/view. However, all my "select' queries are coming with empty results. 

I also try to connect from within the database pod (with username postgres and empty password), connection is fine, yet no data is retrievable via my select statement.

I am writing a simple select statement such as "select * form metrics fetch first 3 rows only".

Also, I have setup logging to true, yet no logging out for the metric messages written out.

    containers:
      - name: pg-adapter
        image: timescale/prometheus-postgresql-adapter:master
        args:
          - "-pg-host=pgprometheus"
          - "-pg-prometheus-log-samples=true"

Any suggestion or advise ?

**Comment by Haybu** [comment]
it turns out to be the sequence in which I created the services in kubernetes.  I needed first to create the DB service then the adapter service before creating the prometheus service, as I reference the DB adapter service name (DNS name) in the "writer" url inside prometheus configmap. No issue, everything works fine after I fix the sequence of how I created the services.

**Comment by erimatnor** [comment]
Hi @Haybu. Glad things are working for you now. I am going to close this issue then.

**Comment by admiral-manjinder** [comment]
@haybu how did you make adapter pod to communicate to the postgre DB pod ? i exposed a cluserIP service for pg-prometheus(DB) pod but still get the below error in adapter logs:

> _level=info ts=2019-05-09T10:17:36.185532049Z caller=log.go:25 config="&{remoteTimeout:30000000000 listenAddr::9201 telemetryPath:/metrics pgPrometheusConfig:{host:pg_prometheus port:5432 user:postgres password: database:postgres schema: sslMode:disable table:metrics copyTable: maxOpenConns:50 maxIdleConns:10 pgPrometheusNormalize:true pgPrometheusLogSamples:true pgPrometheusChunkInterval:43200000000000 useTimescaleDb:true dbConnectRetries:0 readOnly:false} logLevel:debug haGroupLockId:0 restElection:false prometheusTimeout:-1}"
level=info ts=2019-05-09T10:17:36.18570968Z caller=log.go:25 msg="host=pg_prometheus port=5432 user=postgres dbname=postgres password='' sslmode=disable connect_timeout=10"
level=error ts=2019-05-09T10:17:36.201553842Z caller=log.go:33 err="dial tcp: lookup pg_prometheus on 100.64.0.10:53: no such host"
_
