### ISSUE TITLE
Improve the build instructions

### ISSUE THREAD

**Issue by syepes** [timescale/prometheus-postgresql-adapter#15]
Could be improve the build from source instructions, I have tried the below but I have not managed to built it (I am no GO guru)

```
# git clone https://github.com/timescale/prometheus-postgresql-adapter.git /tmp/pg_adapter/src
# export GOPATH=/tmp/pg_adapter
# cd /tmp/pg_adapter/src
# dep ensure
root project import: dep does not currently support using GOPATH/src as the project root
```

Update I have manged to build it but using `godep get`

**Comment by dianasaur323** [comment]
Hi @syepes, @niksajakovljevic just added packaged binaries for linux and darwin, so the install process should be easier now. Let us know if you think this is better :)

https://github.com/timescale/prometheus-postgresql-adapter/releases
