### ISSUE TITLE
docker instructions

### ISSUE THREAD

**Issue by jaberelf** [timescale/prometheus-postgresql-adapter#16]
Hi,
I'm using this adapter for a personal project, and I follow exactly the docker instructions. In the final one I get this Error:
"docker: Error response from daemon: Cannot link to a non running container: /prometheus_postgresql_adapter AS /pedantic_montalcini/prometheus_postgresql_adapter"
I don't if I have to change the path to prometheus.yml, if that's the solution, I want to know how I can determine that path.
Thanks

**Comment by niksajakovljevic** [comment]
Hi @jones96 

just recently we've published a step by step tutorial http://docs.timescale.com/v0.10/tutorials/prometheus-adapter

**Comment by RobAtticus** [comment]
A more up to date link:
https://docs.timescale.com/latest/tutorials/prometheus-adapter
