### ISSUE TITLE
How to connect standalone prometheus to timescaledb

### ISSUE THREAD

**Issue by CassDBA** [timescale/prometheus-postgresql-adapter#20]
Hi 

How to build prometheus-postgresql-adapter for standalone prometheus which is not part of docker.

**Comment by CassDBA** [comment]
Found way , using following
git clone https://github.com/timescale/prometheus-postgresql-adapter.git
cd prometheus-postgresql-adapter
go install

**Comment by erimatnor** [comment]
@CassDBA closing this issue since issue seems resolved.
