### ISSUE TITLE
Q: Can you run this without Docker?

### ISSUE THREAD

**Issue by dannyman** [timescale/prometheus-postgresql-adapter#21]
Is there a way to build and run this software without a Docker image? If this is documented somewhere I'd be happy to submit a PR for the README. Thanks!

-danny

**Comment by sfnke** [comment]
Hi @dannyman,

if you run `make` in the source directory it will build the binary right into that folder. You can then run it with `./prometheus-postgresql-adapter`

**Comment by RobAtticus** [comment]
Yes, what @carazzim0 is correct.

**Comment by dianasaur323** [comment]
Hi @dannyman, @niksajakovljevic just released some binaries for linux and darwin, so hopefully that helps with the install process. I'll go ahead and close this issue!

https://github.com/timescale/prometheus-postgresql-adapter/releases
