### ISSUE TITLE
Prometheus crashes in latest prom/prometheus, but fine in prom/prometheus:v2.2.1 

### ISSUE THREAD

**Issue by subash89** [timescale/prometheus-postgresql-adapter#23]
With the latest tag https://hub.docker.com/r/prom/prometheus/tags/ published 6 days ago from this date, having a regression issue I believe.

Followed exact steps to integrate postgresDB+its metrics exporter, along with prometheus and postgres storage adaptor.

On Postgres DB side I was seeing bunch of following error logs 

LOG:  unexpected EOF on client connection with an open transaction 

And on prometheus side, seen 

panic: runtime error: invalid memory address or nil pointer dereference

and crashed.

**Comment by niksajakovljevic** [comment]
Hi @subash89,

check out our latest tutorial to get started http://docs.timescale.com/v0.10/tutorials/prometheus-adapter

**Comment by niksajakovljevic** [comment]
@subash89 I assume things are running fine for you now. Closing this issue
