### ISSUE TITLE
Cannot set "lc_messages"

### ISSUE THREAD

**Issue by ksyz** [timescale/prometheus-postgresql-adapter#28]
With 9e6c7555a15dea8a229408dd422b1354ba1db442, adapter fails to start as unprivileged user. 

```caller=client.go:99 err="pq: permission denied to set parameter \"lc_messages\""```

As stated in [runtime-config-client.html#GUC-LC-MESSAGES](https://www.postgresql.org/docs/current/static/runtime-config-client.html#GUC-LC-MESSAGES): _Only superusers can change this setting_

**Comment by niksajakovljevic** [comment]
@ksyz thanks for reporting.
This has been addressed with https://github.com/timescale/prometheus-postgresql-adapter/commit/29f7d50f63d35faaf5c4afc88dfb7c6c0ca18f08.
Closing the issue.
