### ISSUE TITLE
how Start Adapter on slave-postgresql-10.5-server?

### ISSUE THREAD

**Issue by skilyazhnev** [timescale/prometheus-postgresql-adapter#39]
Hi, i have master-slave  configuration, and I try to run adapter (read only ) on slave server to balance.
when run with parameters:
         /opt/pg_adapter/prometheus-postgresql-adapter-0.3-linux-amd64 -read.only  -pg.database=prometheus -pg.password=mypass -pg.use-timescaledb=true -pg.user=myuser
adapter write: 
           level=error ts=2018-09-11T10:03:37.967475402Z caller=log.go:33 err="pq: cannot set transaction read-write mode during recovery"
 This configuration is supported by this system? if so, where did I go wrong?

**Comment by niksajakovljevic** [comment]
Hi @skilyazhnev,

unfortunately at the moment you need to have write access to the database as there are some initial checks/function calls to make sure you have valid schema in the DB. The intention of read-only option was to have something like `dry-run` in production (to prevent accidental writes to DB) or for some testing
