### ISSUE TITLE
prometheus-postgresql-adapter fails to connect PostgreSQL 10.

### ISSUE THREAD

**Issue by zhengjf9** [timescale/prometheus-postgresql-adapter#42]
I have updated PostgreSQL to version 10 and set the password authentication as scram-sha-256. Does the adapter support this?

**Comment by niksajakovljevic** [comment]
We use `lib/pq` driver to connect to PostgreSQL. Unfortunately `pq` does not support SCRAM at the moment: https://github.com/lib/pq/pull/608/files
