### ISSUE TITLE
do prometheus-postgresql-adapter contains pg_prometheus?

### ISSUE THREAD

**Issue by naughtyGitCat** [timescale/prometheus-postgresql-adapter#51]
if not,Why not combine together?

**Comment by naughtyGitCat** [comment]
two extension name looks same,make newbee feel confuse to understand.

read from two extension`s readme file,make me feel the two rely on both

**Comment by niksajakovljevic** [comment]
Hi @naughtyGitCat 
you can use only `pg_prometheus` if you want, but if you use `prometheus-postgresql-adapter` then you need to use `pg_prometheus` as well. The extension `pg_prometheus` is db extension where the adapter is http service.
Hope this brings more clarity ;)
