### ISSUE TITLE
Prometheus unable to connect to adapter

### ISSUE THREAD

**Issue by nicklinck** [timescale/prometheus-postgresql-adapter#56]
I am currently running prometheus on a kubernetes cluster (Kubernetes Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0+icp-ee", GitCommit:"9cb64de4ca4d039c35f4a29721aa5cf787648a15", GitTreeState:"clean", BuildDate:"2018-04-27T06:32:18Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"})

I created a kubernetes service so that the containers for pg_prometheus, prometheus_postgresql_adapter, and prometheus can communicate with each other. The .yaml file I used to create this is:

apiVersion: v1
kind: Service
metadata:
name: pg-prometheus-service
&nbsp;&nbsp;namespace: "data-collection"
&nbsp;&nbsp;labels:
&nbsp;&nbsp;&nbsp;&nbsp;collect: data
spec:
&nbsp;&nbsp;selector:
&nbsp;&nbsp;&nbsp;&nbsp;collect: data 
&nbsp;&nbsp;ports:
&nbsp;&nbsp;\- name: pg-prometheus
&nbsp;&nbsp;&nbsp;&nbsp;protocol: TCP
&nbsp;&nbsp;&nbsp;&nbsp;port: 5432
&nbsp;&nbsp;&nbsp;&nbsp;targetPort: 5432
&nbsp;&nbsp; \- name: postgresql-adapter
&nbsp;&nbsp;&nbsp;&nbsp;protocol: TCP
&nbsp;&nbsp;&nbsp;&nbsp;port: 9201
&nbsp;&nbsp;&nbsp;&nbsp;targetPort: 9201

I created the pg_prometheus deployment using the following .yaml file:

apiVersion: apps/v1
kind: Deployment
metadata:
&nbsp;&nbsp;name: pg-prometheus
&nbsp;&nbsp;namespace: data-collection
&nbsp;&nbsp;labels:
&nbsp;&nbsp;&nbsp;&nbsp;collect: data
spec:
&nbsp;&nbsp;selector:
&nbsp;&nbsp;&nbsp;&nbsp;matchLabels:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;collect: data 
&nbsp;&nbsp;replicas: 1
&nbsp;&nbsp;template:
&nbsp;&nbsp;&nbsp;&nbsp;metadata:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;labels:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;collect: data
&nbsp;&nbsp;&nbsp;&nbsp;spec:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;containers:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\- name: pg-prometheus
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;image: timescale/pg_prometheus:master
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ports:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\- containerPort: 5432
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;args: ["postgres", "-csynchronous_commit=off"]

and I created the adapter deployment using the following .yaml file:

apiVersion: apps/v1
kind: Deployment
metadata:
&nbsp;&nbsp;name: prometheus-postgresql-adapter
&nbsp;&nbsp;namespace: data-collection
&nbsp;&nbsp;labels:
&nbsp;&nbsp;&nbsp;&nbsp;collect: data
spec:
&nbsp;&nbsp;selector:
&nbsp;&nbsp;&nbsp;&nbsp;matchLabels:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;collect: data 
&nbsp;&nbsp;replicas: 1
&nbsp;&nbsp;template:
&nbsp;&nbsp;&nbsp;&nbsp;metadata:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;labels:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;collect: data
&nbsp;&nbsp;&nbsp;&nbsp;spec:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;containers:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- name: prometheus-postgresql-adapter
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;image: timescale/prometheus-postgresql-adapter:master
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ports:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- containerPort: 9201
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;args: ["-pg.host=pg-prometheus-service", "-pg.prometheus-log-samples"]`

when connecting to pg-prometheus I see that the database schema has been created:

postgres=# \dt
             List of relations
 Schema |&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Name&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;Type&nbsp;|&nbsp;Owner   
--------+----------------+-------+----------
 public | metrics_copy   | table | postgres
 public | metrics_labels | table | postgres
 public | metrics_values | table | postgres
(3 rows)

Prometheus and the node exporter have been running on the cluster as expected, I have just been trying to add on the remote_write feature. The problem that I am having is when I load prometheus (which is in the kube-system namespace). I edit the configmap for my prometheus deployment so that in the prometheus.yml file I have:

prometheus.yml:
global:
&nbsp;&nbsp;scrape_interval: 1m
&nbsp;&nbsp;evaluation_interval: 1m

rule_files:
&nbsp;&nbsp;- /etc/alert-rules/*.rules
&nbsp;&nbsp;- /etc/alert-rules/*.yml

scrape_configs:
&nbsp;&nbsp;- job_name: prometheus
&nbsp;&nbsp;&nbsp;&nbsp;static_configs:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- targets:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- localhost:9090

remote_write:
&nbsp;&nbsp;- url: "http://pg-prometheus-service.data-collection:9201/write"
...
(much more in the configuration file)

I then restart the prometheus deployment and get the following error:

level=info ts=2019-01-11T01:31:42.871609412Z caller=main.go:394 msg="Loading configuration file" filename=/etc/config/prometheus.yml
level=error ts=2019-01-11T01:31:42.874975125Z caller=main.go:356 msg="Error loading config" err="couldn't load configuration (--config.file=/etc/config/prometheus.yml): url for remote_write is empty"

I have tried many different options for the url parameter with no success (getting rid of http://, not including the service namespace, using the IP address rather than the service name, not including /write...). 

On my kubernetes cluster I am also running a kube-dns service to handle domain name resolutions. 

Any advice on what might be going wrong would be greatly appreciated! Thanks!

**Comment by niksajakovljevic** [comment]
@nicklinck You should go into prometheus container, `cat /etc/config/prometheus.yml` and inspect the config file. You can share it here as well. Seems there might be some problem in your config map for prometheus.

**Comment by nicklinck** [comment]
@niksajakovljevic here is my prometheus.yml file: 
[prometheus.yml](https://github.com/timescale/prometheus-postgresql-adapter/files/2750660/prometheus.txt)

**Comment by niksajakovljevic** [comment]
@nicklinck I think that url should be within single quotes, not double. BTW there is a `promtool` (binary that comes with Prometheus) that can validate the config file: `./promtool check config prometheus.yml`

**Comment by nicklinck** [comment]
@niksajakovljevic Thank you, using promtool I realized that I put the remote_write option right in the middle of the scrape configs option. Updated yml: [prometheus.yml](https://github.com/timescale/prometheus-postgresql-adapter/files/2751541/prometheus.txt)

However, I am still not seeing any data in pg-prometheus. From my grafana dashboard I can see that data is being sent to the adapter but not much is being sent to pg-prometheus.
<img width="538" alt="screen shot 2019-01-11 at 4 42 32 pm" src="https://user-images.githubusercontent.com/10569344/51066598-07c89200-15c0-11e9-8809-8d1574864c90.png">

In the adapter yaml I specified "-pg.host=pg-prometheus-service", where pg-prometheus-service is a service that should route all data for port 5432 to pg-prometheus. 

Also, in the log files for pg-prometheus, it says 
LOG:  the "timescaledb" extension is not up-to-date
The most up-to-date version is 1.1.1, the installed version is 0.12.1

I tried running: postgres=# ALTER EXTENSION timescaledb UPDATE; 
but received: NOTICE:  version "0.12.1" of extension "timescaledb" is already installed

**Comment by nicklinck** [comment]
@niksajakovljevic do I need to include remote_read as well for this to work?

**Comment by nicklinck** [comment]
@niksajakovljevic I tried pulling the images from :latest rather than :master but I am still not getting any data sent to the pg-prometheus database. The adapter is able to create the database but it is not putting anything into it.

**Comment by nicklinck** [comment]
@niksajakovljevic That solved it! Thank you! My remote_write was interfering with scrape_configs so I just had to move remote_write above it in the yaml file.
