### ISSUE TITLE
HTTP 400 : Bad wiretype

### ISSUE THREAD

**Issue by YoannMa** [timescale/prometheus-postgresql-adapter#6]
Hello,

I was trying to setup Prometheus with TimescaleDB.

- Prometheus 2.0
- PostgreSQL 10.1
- TimescaleDB 0.8.0
- PostgreSQL Prometheus plugin `master`
- Prometheus PostgreSQL Adapter (docker) `latest`

But when I set the prometheus' configuration as given in the documentation, I have this error :

```
level=warn ts=2018-01-09T13:40:01.162965791Z caller=queue_manager.go:485 component=remote msg="Error sending samples to remote storage" count=100 err="server returned HTTP status 400 Bad Request: proto: bad wiretype for field remote.Query.StartTimestampMs: got wiretype 2, want 0"
```

Is the prometheus version too recent ?

**Comment by erimatnor** [comment]
Hi @YoannMa. It appears that Prometheus 2.0 has incompatible changes to the wire protocol for remote storage. We will move to the new protocol in an upcoming release of the adapter.

**Comment by JoeyG1973** [comment]
Any ideas when the next release will be that will be compatible with prom 2.x?  We kinda need it. :)  Also we might be able to throw a resource at it if you are willing to accept the help.  :)

**Comment by erimatnor** [comment]
@JoeyG1973 Hopefully this week. Currently testing internally.

**Comment by JoeyG1973** [comment]
@erimatnor Not that we are waiting or anything but you know.... *twiddle*

;)

**Comment by erimatnor** [comment]
@JoeyG1973 sorry for the holdup. Just released v0.2. Note that this release has some changes to command-line parameters so you might need to update your launch configuration.

**Comment by YoannMa** [comment]
~It seems I'm still getting the issue with the v0.2 release~

EDIT :

My bad, I had a problem in my config, it's working without issue :ok_hand:

**Comment by erimatnor** [comment]
Ok, closing this issue since issue seems resolved.
