### ISSUE TITLE
How to use prometheus-postgresql-adapter with kube-prometheus on K8s cluster?

### ISSUE THREAD

**Issue by mcinquin** [timescale/prometheus-postgresql-adapter#61]
Hello,

I have a K8s cluster installed with Kubespray and monitored with kube-prometheus (based on prometheus-operator).
I have trouble seeing how I can specify a different remote_write (with different ip and port) to my 2 prometheus instances.
Has anyone ever tested it?

Regards.

**Comment by mcinquin** [comment]
up

**Comment by gjpei2** [comment]
i guess can deploy it with pg_prometheus in one delployment

**Comment by mcinquin** [comment]
I don't think a deployment resolve the problem.
But thanks for your reply.

In view of my tests and the reactivity of the project, I gave up postgresql as LTS.
