### ISSUE TITLE
launch without docker

### ISSUE THREAD

**Issue by 6-10** [timescale/prometheus-postgresql-adapter#8]
Hi,

I'm using Prometheus 2.2.0 to generate some metrics and I need long term storage. 
Is there a way to use this adapter for PostgreSQL without docker ?

Thank you

**Comment by erimatnor** [comment]
@Adibouz absolutely. There is no Docker requirement to use the adapter. We currently do not provide binary releases, but you can just `go get` the adapter and run directly on a bare-bones machine.
