### ISSUE TITLE
Oudated binaries / docker image

### ISSUE THREAD

**Issue by Neraud** [timescale/prometheus-postgresql-adapter#86]
The most recent release or docker image I can find is v0.4.1 (2018-10-17).

The current README lists features that are not available in this old v.0.4.1.
For example, using `TS_PROM_*` environment variables doesn't work.
(building from source works fine ofc)

I see you already have an enhancement to automatically build docker images (#33).

But waiting for it, could you please release a new version and docker image when important changes are pushed ?

**Comment by bboule** [comment]
You should now be able to pull v0.5.0 via docker please re-open if you have any issues.
