### ISSUE TITLE
Logging plaintext password

### ISSUE THREAD

**Issue by andersflemmen** [timescale/prometheus-postgresql-adapter#95]
The adapter seems to be logging the PostgreSQL password in plaintext on startup. Is this intended? Would be nice if it didn't.

**Comment by bboule** [comment]
@andersflemmen  let me have a look at this and see what we can do in the short term.

**Comment by ashutoshgngwr** [comment]
> let me have a look at this and see what we can do in the short term.

@bboule not log the password in plain text?

**Comment by aletundo** [comment]
Hi @andersflemmen ,@RobAtticus, @bboule and @ashutoshgngwr 

This issue is merged since months but still affects the latest Docker Image available on Docker Hub (tags: 0.6.0, master and latest) (see #102).
